name: dart_datachannel_example
description: Pure Dart CLI client for flutter_datachannel.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  dart_datachannel:
    path: ../

dev_dependencies:
  lints: ^5.0.0

executables:
  fdc_client: client
